version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: src/AsyncProjectionStressTest.Api/Dockerfile
    ports:
      - "80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Marten__ConnectionString: Host=db;Database=postgres;UserId=postgres;Password=APST123;pooling=true;timeout=100;
    depends_on:
      - db
    deploy:
      mode: replicated
      replicas: 5

  projection:
    build:
      context: .
      dockerfile: src/AsyncProjectionStressTest.EventProjection/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Marten__ConnectionString: Host=db;Database=postgres;UserId=postgres;Password=APST123;pooling=true;timeout=100;
    depends_on:
      - db
    deploy:
      mode: replicated
      replicas: 3

  clienttester:
    build:
      context: .
      dockerfile: src/AsyncProjectionStressTest.AutoClientTester/Dockerfile
    depends_on:
      - api
      - projection
    deploy:
      mode: replicated
      replicas: 15

  db:
    image: docker.io/postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: APST123
    volumes:
      - db_vol:/var/lib/postgresql/data

volumes:
  db_vol: